### ISSUE TITLE
Compatibility with 'Floating Navbar'

### ISSUE THREAD

**Issue by Naugrimohtar** [Kragrathea/OctoPrint-PrettyGCode#34] opened 2020-08-18 02:41 UTC
It seems that there is an issue with this plugin, in full screen mode, with another plugin 'Floating Navbar' where the title bar conflicts with this plugins top buttons.
![Capture](https://user-images.githubusercontent.com/28710488/90464161-54e0e400-e0d2-11ea-86d8-76eedf166740.PNG)

**Comment by Deses** [comment] 2020-08-18 10:49
I confirm this issue, it's also happening to me.

Floating navbar buffer is set to 20px, which I think is the default.

**Comment by Kragrathea** [comment] 2020-08-18 19:49
Hmm. The obvious fix would be to move the buttons down. But then then would look funny if you don't have the Floating Nav bar. How about this for a temp fix. Add this CSS to the "Additional CSS" section of the PrettyGCode tab. It will move those four buttons to 40px down from the top.

`.fstoggle{
  top:40px !important;
}
.pgstatetoggle{
  top:40px !important;
}
.pgfilestoggle{
  top:40px !important;
}
.pgsettingstoggle{
  top:40px !important;
}`

**Comment by Deses** [comment] 2020-08-18 20:44
Hey thanks for the that snippet! Based on that I tweaked it a little bit more and here's what I'm using:

`.fstoggle{ top:45px !important; }
.pgstatetoggle{ top:45px !important; }
.pgfilestoggle{ top:45px !important; }
.pgsettingstoggle{ top:45px !important; }
#myslider{ top:7% !important; }
#state_wrapper{ top:80px !important; }
#files_wrapper{ top:80px !important; }`

**Comment by sr1329** [comment] 2020-08-18 21:07
Oh gosh wonderful fix! Now the only issue is the white on white text on the accordion sidebar.

**Comment by Deses** [comment] 2020-08-18 21:31
>Now the only issue is the white on white text on the accordion sidebar.

I don't see any white on white text! 🤔 Care to share a screenshot, please?

**Comment by sr1329** [comment] 2020-08-18 21:47
Yes let me try on my phone. Keep in mind I am using a plug in called themify and it’s default theme which makes all text white and the background dark. It is like a “dark mode” for octoprint.

**Comment by KenLucke** [comment] 2020-08-18 21:57
Confirmed (I was just comig to report this and see the thread already).  Not only does it hide info when FNB is on, but parts of the Dashboard are hidden even when it is not:

ON:
![CR-10 v2 (Red) LAN  OctoPrint  0% - 2020-08-18 14-52-15](https://user-images.githubusercontent.com/57936294/90569514-da13d980-e162-11ea-82d7-a177ed3560b5.jpg)

OFF:
![CR-10v2 (Blue) LAN  OctoPrint  - 35% 2020-08-18 14-53-43](https://user-images.githubusercontent.com/57936294/90569588-ffa0e300-e162-11ea-92b2-200061907d51.jpg)

**Comment by LarryVand** [comment] 2020-08-18 23:07
Sorry if this is in the wrong place but are are all the settings supposed to be saved somehow?? Like the additional CSS code (just discussed) and more importantly to me all the view settings?? Because every time I start Octoprint I have to go into view settings and turn off the Orbit When Idle flag and turn on Sync To Progress... and I apologize if this question has been asked and answered before... Thank you.

**Comment by Kragrathea** [comment] 2020-08-18 23:22
> Sorry if this is in the wrong place but are all the settings supposed to be saved somehow?? Like the additional CSS code (just discussed) and more importantly to me all the view settings?? Because every time I start Octoprint I have to go into view settings and turn off the Orbit When Idle flag and turn on Sync To Progress... and I apologize if this question has been asked and answered before... Thanks.

Those settings are saved in the cookies in the browser. And there are separate settings if you use the direct to FullScreen URL. If it still isn't working start a new Issue on it.

**Comment by LarryVand** [comment] 2020-08-19 02:49
Thanks for the reply. I opened a new issue #43 https://github.com/Kragrathea/OctoPrint-PrettyGCode/issues/43

**Comment by sr1329** [comment] 2020-08-19 04:01
Did a new install on Octopi 18 64 bit. text is fixed and so is dashboard. Wow very quick. Also noticed anti-alias. Really cool.

**Comment by Kragrathea** [comment] 2020-08-19 23:55
I might do a different fix for this down the road. But closing for now.

**Closed** 2020-08-19 23:55 UTC
